// Code generated by clients/gen_dialect.py from opendaisugi.dialect. DO NOT EDIT.

/// `dialect.DIALECT_JSON`: the canonical JSON the hash is taken over.
pub const DIALECT_JSON: &str = "{\"glob_regex\":1,\"synonyms\":{\"file_content_preservation\":\"keep_unchanged\",\"file_immutability\":\"keep_unchanged\",\"file_immutable\":\"keep_unchanged\",\"file_preservation\":\"keep_unchanged\",\"file_unchanged\":\"keep_unchanged\",\"files_not_modified\":\"keep_unchanged\",\"filesystem_readonly\":\"keep_unchanged\",\"immutable_source\":\"keep_unchanged\",\"no_file_modification\":\"keep_unchanged\",\"no_file_modifications\":\"keep_unchanged\",\"no_file_mutations\":\"keep_unchanged\",\"no_file_writes\":\"keep_unchanged\",\"no_filesystem_mutation\":\"keep_unchanged\",\"no_local_modification\":\"keep_unchanged\",\"no_local_modifications\":\"keep_unchanged\",\"no_modification\":\"keep_unchanged\",\"no_modifications\":\"keep_unchanged\",\"no_project_modification\":\"keep_unchanged\",\"no_source_modification\":\"keep_unchanged\",\"read_only\":\"keep_unchanged\",\"read_only_access\":\"keep_unchanged\",\"read_only_operation\":\"keep_unchanged\",\"read_only_operations\":\"keep_unchanged\"},\"version\":1,\"words\":{\"keep_unchanged\":{\"body\":{\"op\":\"forall_steps\",\"pred\":{\"op\":\"forall_writes\",\"pred\":{\"op\":\"not_matches\",\"path\":\"path\",\"regex\":\"$target\"}}},\"params\":[{\"default\":\"**\",\"name\":\"target\",\"sort\":\"glob\"}]}},\"write_paths\":2}";

/// `dialect.DIALECT_HASH`.
pub const DIALECT_HASH: &str = "108a89a256798dfc";

/// `dialect.AUDIT_PREFIX`.
pub const AUDIT_PREFIX: &str = "dialect audit: ";

/// `dialect.MAX_GLOB_CHARS`.
pub const MAX_GLOB_CHARS: usize = 1024;
/// `dialect.MAX_GLOB_DOUBLE_STARS`.
pub const MAX_GLOB_DOUBLE_STARS: usize = 4;
/// `dialect.MAX_GLOB_STARS`.
pub const MAX_GLOB_STARS: usize = 16;

/// `dialect.WORDS`: (word, glob parameter, its default, body JSON).
pub const WORDS: &[(&str, &str, &str, &str)] = &[
    ("keep_unchanged", "target", "**", "{\"op\":\"forall_steps\",\"pred\":{\"op\":\"forall_writes\",\"pred\":{\"op\":\"not_matches\",\"path\":\"path\",\"regex\":\"$target\"}}}"),
];

/// `dialect.SYNONYMS`: (type name, word).
pub const SYNONYMS: &[(&str, &str)] = &[
    ("file_content_preservation", "keep_unchanged"),
    ("file_immutability", "keep_unchanged"),
    ("file_immutable", "keep_unchanged"),
    ("file_preservation", "keep_unchanged"),
    ("file_unchanged", "keep_unchanged"),
    ("files_not_modified", "keep_unchanged"),
    ("filesystem_readonly", "keep_unchanged"),
    ("immutable_source", "keep_unchanged"),
    ("no_file_modification", "keep_unchanged"),
    ("no_file_modifications", "keep_unchanged"),
    ("no_file_mutations", "keep_unchanged"),
    ("no_file_writes", "keep_unchanged"),
    ("no_filesystem_mutation", "keep_unchanged"),
    ("no_local_modification", "keep_unchanged"),
    ("no_local_modifications", "keep_unchanged"),
    ("no_modification", "keep_unchanged"),
    ("no_modifications", "keep_unchanged"),
    ("no_project_modification", "keep_unchanged"),
    ("no_source_modification", "keep_unchanged"),
    ("read_only", "keep_unchanged"),
    ("read_only_access", "keep_unchanged"),
    ("read_only_operation", "keep_unchanged"),
    ("read_only_operations", "keep_unchanged"),
];

/// One command of `write_paths.WRITERS`: its rule and the closed flag
/// sets it may carry.
pub struct WriterSpec {
    pub rule: &'static str,
    pub short: &'static str,
    pub short_value: &'static str,
    pub short_optional: &'static str,
    pub long: &'static [&'static str],
    pub long_value: &'static [&'static str],
    pub long_optional: &'static [&'static str],
}

/// `write_paths.WRITERS`, by command name.
pub const WRITERS: &[(&str, WriterSpec)] = &[
    ("cp", WriterSpec {
        rule: "dest",
        short: "adfiHlLnPpRrsTuvx",
        short_value: "t",
        short_optional: "",
        long: &["--archive", "--dereference", "--force", "--interactive", "--link", "--no-clobber", "--no-dereference", "--no-target-directory", "--one-file-system", "--recursive", "--remove-destination", "--strip-trailing-slashes", "--symbolic-link", "--verbose"],
        long_value: &["--target-directory"],
        long_optional: &["--preserve", "--reflink", "--update"],
    }),
    ("dd", WriterSpec {
        rule: "dd",
        short: "",
        short_value: "",
        short_optional: "",
        long: &[],
        long_value: &[],
        long_optional: &[],
    }),
    ("install", WriterSpec {
        rule: "install",
        short: "cCdDpsTv",
        short_value: "gmot",
        short_optional: "",
        long: &["--compare", "--directory", "--no-target-directory", "--preserve-timestamps", "--strip", "--verbose"],
        long_value: &["--group", "--mode", "--owner", "--target-directory"],
        long_optional: &[],
    }),
    ("ln", WriterSpec {
        rule: "dest",
        short: "finLPrsTv",
        short_value: "t",
        short_optional: "",
        long: &["--force", "--interactive", "--logical", "--no-dereference", "--no-target-directory", "--physical", "--relative", "--symbolic", "--verbose"],
        long_value: &["--target-directory"],
        long_optional: &[],
    }),
    ("mkdir", WriterSpec {
        rule: "all",
        short: "pv",
        short_value: "m",
        short_optional: "",
        long: &["--parents", "--verbose"],
        long_value: &["--mode"],
        long_optional: &[],
    }),
    ("mv", WriterSpec {
        rule: "move",
        short: "finTuv",
        short_value: "t",
        short_optional: "",
        long: &["--force", "--interactive", "--no-clobber", "--no-target-directory", "--strip-trailing-slashes", "--verbose"],
        long_value: &["--target-directory"],
        long_optional: &["--update"],
    }),
    ("rm", WriterSpec {
        rule: "all",
        short: "dfiIrRv",
        short_value: "",
        short_optional: "",
        long: &["--dir", "--force", "--no-preserve-root", "--one-file-system", "--recursive", "--verbose"],
        long_value: &[],
        long_optional: &["--interactive", "--preserve-root"],
    }),
    ("rmdir", WriterSpec {
        rule: "all",
        short: "v",
        short_value: "",
        short_optional: "",
        long: &["--ignore-fail-on-non-empty", "--verbose"],
        long_value: &[],
        long_optional: &[],
    }),
    ("rsync", WriterSpec {
        rule: "rsync",
        short: "0346aAbcCdDEgHhiIkKlLmnoOpPqrRsStuUvWxXyz",
        short_value: "Bef",
        short_optional: "",
        long: &["--acls", "--append", "--archive", "--backup", "--checksum", "--compress", "--copy-links", "--cvs-exclude", "--delete", "--delete-after", "--delete-before", "--delete-delay", "--delete-during", "--delete-excluded", "--devices", "--dirs", "--dry-run", "--executability", "--existing", "--force", "--fuzzy", "--group", "--hard-links", "--human-readable", "--ignore-existing", "--ignore-times", "--inplace", "--itemize-changes", "--links", "--list-only", "--mkpath", "--no-group", "--no-owner", "--no-perms", "--no-relative", "--no-times", "--no-whole-file", "--numeric-ids", "--omit-dir-times", "--one-file-system", "--owner", "--partial", "--perms", "--progress", "--protect-args", "--prune-empty-dirs", "--quiet", "--recursive", "--relative", "--remove-source-files", "--safe-links", "--size-only", "--sparse", "--specials", "--stats", "--times", "--update", "--verbose", "--whole-file", "--xattrs"],
        long_value: &["--block-size", "--bwlimit", "--chmod", "--chown", "--compress-level", "--contimeout", "--debug", "--exclude", "--exclude-from", "--files-from", "--filter", "--include", "--include-from", "--info", "--max-delete", "--max-size", "--min-size", "--modify-window", "--out-format", "--port", "--rsh", "--suffix", "--timeout"],
        long_optional: &[],
    }),
    ("sed", WriterSpec {
        rule: "sed",
        short: "Enrsuz",
        short_value: "efl",
        short_optional: "i",
        long: &["--debug", "--follow-symlinks", "--null-data", "--posix", "--quiet", "--regexp-extended", "--sandbox", "--separate", "--silent", "--unbuffered"],
        long_value: &["--expression", "--file", "--line-length"],
        long_optional: &["--in-place"],
    }),
    ("shred", WriterSpec {
        rule: "all",
        short: "fuvxz",
        short_value: "ns",
        short_optional: "",
        long: &["--exact", "--force", "--verbose", "--zero"],
        long_value: &["--iterations", "--size"],
        long_optional: &["--remove"],
    }),
    ("tee", WriterSpec {
        rule: "all",
        short: "aip",
        short_value: "",
        short_optional: "",
        long: &["--append", "--ignore-interrupts"],
        long_value: &[],
        long_optional: &["--output-error"],
    }),
    ("touch", WriterSpec {
        rule: "all",
        short: "acm",
        short_value: "dtr",
        short_optional: "",
        long: &[],
        long_value: &["--date", "--reference"],
        long_optional: &[],
    }),
    ("truncate", WriterSpec {
        rule: "all",
        short: "co",
        short_value: "rs",
        short_optional: "",
        long: &["--io-blocks", "--no-create"],
        long_value: &["--reference", "--size"],
        long_optional: &[],
    }),
    ("unlink", WriterSpec {
        rule: "all",
        short: "",
        short_value: "",
        short_optional: "",
        long: &[],
        long_value: &[],
        long_optional: &[],
    }),
];

/// `write_paths.DD_KEYS`.
pub const DD_KEYS: &[&str] = &[
    "bs",
    "cbs",
    "conv",
    "count",
    "ibs",
    "if",
    "iflag",
    "iseek",
    "obs",
    "of",
    "oflag",
    "oseek",
    "seek",
    "skip",
    "status",
];
