// Code generated by clients/gen_dialect.py from opendaisugi.dialect. DO NOT EDIT.

package verify

// DialectJSON is dialect.DIALECT_JSON: the canonical JSON the hash is taken over.
const DialectJSON = "{\"glob_regex\":1,\"synonyms\":{\"file_content_preservation\":\"keep_unchanged\",\"file_immutability\":\"keep_unchanged\",\"file_immutable\":\"keep_unchanged\",\"file_preservation\":\"keep_unchanged\",\"file_unchanged\":\"keep_unchanged\",\"files_not_modified\":\"keep_unchanged\",\"filesystem_readonly\":\"keep_unchanged\",\"immutable_source\":\"keep_unchanged\",\"no_file_modification\":\"keep_unchanged\",\"no_file_modifications\":\"keep_unchanged\",\"no_file_mutations\":\"keep_unchanged\",\"no_file_writes\":\"keep_unchanged\",\"no_filesystem_mutation\":\"keep_unchanged\",\"no_local_modification\":\"keep_unchanged\",\"no_local_modifications\":\"keep_unchanged\",\"no_modification\":\"keep_unchanged\",\"no_modifications\":\"keep_unchanged\",\"no_project_modification\":\"keep_unchanged\",\"no_source_modification\":\"keep_unchanged\",\"read_only\":\"keep_unchanged\",\"read_only_access\":\"keep_unchanged\",\"read_only_operation\":\"keep_unchanged\",\"read_only_operations\":\"keep_unchanged\"},\"version\":1,\"words\":{\"keep_unchanged\":{\"body\":{\"op\":\"forall_steps\",\"pred\":{\"op\":\"forall_writes\",\"pred\":{\"op\":\"not_matches\",\"path\":\"path\",\"regex\":\"$target\"}}},\"params\":[{\"default\":\"**\",\"name\":\"target\",\"sort\":\"glob\"}]}},\"write_paths\":2}"

// DialectHash is dialect.DIALECT_HASH.
const DialectHash = "108a89a256798dfc"

// DialectAuditPrefix is dialect.AUDIT_PREFIX.
const DialectAuditPrefix = "dialect audit: "

// The limits of a supported target glob (dialect.MAX_GLOB_*).
const (
	maxGlobChars       = 1024
	maxGlobDoubleStars = 4
	maxGlobStars       = 16
)

// dialectWord is one word of dialect.WORDS: its one glob parameter and body.
type dialectWord struct {
	Param, Default, Body string
}

// dialectWords is dialect.WORDS.
var dialectWords = map[string]dialectWord{
	"keep_unchanged": {Param: "target", Default: "**", Body: "{\"op\":\"forall_steps\",\"pred\":{\"op\":\"forall_writes\",\"pred\":{\"op\":\"not_matches\",\"path\":\"path\",\"regex\":\"$target\"}}}"},
}

// dialectSynonyms is dialect.SYNONYMS.
var dialectSynonyms = map[string]string{
	"file_content_preservation": "keep_unchanged",
	"file_immutability":         "keep_unchanged",
	"file_immutable":            "keep_unchanged",
	"file_preservation":         "keep_unchanged",
	"file_unchanged":            "keep_unchanged",
	"files_not_modified":        "keep_unchanged",
	"filesystem_readonly":       "keep_unchanged",
	"immutable_source":          "keep_unchanged",
	"no_file_modification":      "keep_unchanged",
	"no_file_modifications":     "keep_unchanged",
	"no_file_mutations":         "keep_unchanged",
	"no_file_writes":            "keep_unchanged",
	"no_filesystem_mutation":    "keep_unchanged",
	"no_local_modification":     "keep_unchanged",
	"no_local_modifications":    "keep_unchanged",
	"no_modification":           "keep_unchanged",
	"no_modifications":          "keep_unchanged",
	"no_project_modification":   "keep_unchanged",
	"no_source_modification":    "keep_unchanged",
	"read_only":                 "keep_unchanged",
	"read_only_access":          "keep_unchanged",
	"read_only_operation":       "keep_unchanged",
	"read_only_operations":      "keep_unchanged",
}

// writerSpec is one command of write_paths.WRITERS: its rule and the
// closed flag sets it may carry.
type writerSpec struct {
	Name, Rule, Short, ShortValue, ShortOptional string
	Long, LongValue, LongOptional                []string
}

// writerList is write_paths.WRITERS, by name.
var writerList = []writerSpec{
	{Name: "cp", Rule: "dest", Short: "adfiHlLnPpRrsTuvx", ShortValue: "t", Long: []string{"--archive", "--dereference", "--force", "--interactive", "--link", "--no-clobber", "--no-dereference", "--no-target-directory", "--one-file-system", "--recursive", "--remove-destination", "--strip-trailing-slashes", "--symbolic-link", "--verbose"}, LongValue: []string{"--target-directory"}, LongOptional: []string{"--preserve", "--reflink", "--update"}},
	{Name: "dd", Rule: "dd"},
	{Name: "install", Rule: "install", Short: "cCdDpsTv", ShortValue: "gmot", Long: []string{"--compare", "--directory", "--no-target-directory", "--preserve-timestamps", "--strip", "--verbose"}, LongValue: []string{"--group", "--mode", "--owner", "--target-directory"}},
	{Name: "ln", Rule: "dest", Short: "finLPrsTv", ShortValue: "t", Long: []string{"--force", "--interactive", "--logical", "--no-dereference", "--no-target-directory", "--physical", "--relative", "--symbolic", "--verbose"}, LongValue: []string{"--target-directory"}},
	{Name: "mkdir", Rule: "all", Short: "pv", ShortValue: "m", Long: []string{"--parents", "--verbose"}, LongValue: []string{"--mode"}},
	{Name: "mv", Rule: "move", Short: "finTuv", ShortValue: "t", Long: []string{"--force", "--interactive", "--no-clobber", "--no-target-directory", "--strip-trailing-slashes", "--verbose"}, LongValue: []string{"--target-directory"}, LongOptional: []string{"--update"}},
	{Name: "rm", Rule: "all", Short: "dfiIrRv", Long: []string{"--dir", "--force", "--no-preserve-root", "--one-file-system", "--recursive", "--verbose"}, LongOptional: []string{"--interactive", "--preserve-root"}},
	{Name: "rmdir", Rule: "all", Short: "v", Long: []string{"--ignore-fail-on-non-empty", "--verbose"}},
	{Name: "rsync", Rule: "rsync", Short: "0346aAbcCdDEgHhiIkKlLmnoOpPqrRsStuUvWxXyz", ShortValue: "Bef", Long: []string{"--acls", "--append", "--archive", "--backup", "--checksum", "--compress", "--copy-links", "--cvs-exclude", "--delete", "--delete-after", "--delete-before", "--delete-delay", "--delete-during", "--delete-excluded", "--devices", "--dirs", "--dry-run", "--executability", "--existing", "--force", "--fuzzy", "--group", "--hard-links", "--human-readable", "--ignore-existing", "--ignore-times", "--inplace", "--itemize-changes", "--links", "--list-only", "--mkpath", "--no-group", "--no-owner", "--no-perms", "--no-relative", "--no-times", "--no-whole-file", "--numeric-ids", "--omit-dir-times", "--one-file-system", "--owner", "--partial", "--perms", "--progress", "--protect-args", "--prune-empty-dirs", "--quiet", "--recursive", "--relative", "--remove-source-files", "--safe-links", "--size-only", "--sparse", "--specials", "--stats", "--times", "--update", "--verbose", "--whole-file", "--xattrs"}, LongValue: []string{"--block-size", "--bwlimit", "--chmod", "--chown", "--compress-level", "--contimeout", "--debug", "--exclude", "--exclude-from", "--files-from", "--filter", "--include", "--include-from", "--info", "--max-delete", "--max-size", "--min-size", "--modify-window", "--out-format", "--port", "--rsh", "--suffix", "--timeout"}},
	{Name: "sed", Rule: "sed", Short: "Enrsuz", ShortValue: "efl", ShortOptional: "i", Long: []string{"--debug", "--follow-symlinks", "--null-data", "--posix", "--quiet", "--regexp-extended", "--sandbox", "--separate", "--silent", "--unbuffered"}, LongValue: []string{"--expression", "--file", "--line-length"}, LongOptional: []string{"--in-place"}},
	{Name: "shred", Rule: "all", Short: "fuvxz", ShortValue: "ns", Long: []string{"--exact", "--force", "--verbose", "--zero"}, LongValue: []string{"--iterations", "--size"}, LongOptional: []string{"--remove"}},
	{Name: "tee", Rule: "all", Short: "aip", Long: []string{"--append", "--ignore-interrupts"}, LongOptional: []string{"--output-error"}},
	{Name: "touch", Rule: "all", Short: "acm", ShortValue: "dtr", LongValue: []string{"--date", "--reference"}},
	{Name: "truncate", Rule: "all", Short: "co", ShortValue: "rs", Long: []string{"--io-blocks", "--no-create"}, LongValue: []string{"--reference", "--size"}},
	{Name: "unlink", Rule: "all"},
}

// ddKeyList is write_paths.DD_KEYS.
var ddKeyList = []string{"bs", "cbs", "conv", "count", "ibs", "if", "iflag", "iseek", "obs", "of", "oflag", "oseek", "seek", "skip", "status"}
