package verify

import (
	"bufio"
	"encoding/json"
	"os"
	"reflect"
	"testing"
)

// shlex_fixture.jsonl is generated by clients/go/probe_shlex.py running the
// REAL Python shlex.split(s, posix=True) — see that file's docstring to
// regenerate. Differential test, not a hand-derived one: every row is what
// cpython actually produced.
func TestPosixSplitAgainstPythonFixture(t *testing.T) {
	f, err := os.Open("testdata/shlex_fixture.jsonl")
	if err != nil {
		t.Fatalf("open fixture: %v", err)
	}
	defer f.Close()

	type row struct {
		Command string   `json:"command"`
		Tokens  []string `json:"tokens"`
		Error   string   `json:"error"`
	}

	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1<<20)
	n := 0
	for sc.Scan() {
		line := sc.Text()
		if line == "" {
			continue
		}
		var r row
		if err := json.Unmarshal([]byte(line), &r); err != nil {
			t.Fatalf("bad fixture line %q: %v", line, err)
		}
		n++
		got, err := posixSplit(r.Command)
		if r.Error != "" {
			if err == nil {
				t.Errorf("command %q: expected error %q, got tokens %v", r.Command, r.Error, got)
			}
			continue
		}
		if err != nil {
			t.Errorf("command %q: unexpected error: %v", r.Command, err)
			continue
		}
		if len(got) == 0 && len(r.Tokens) == 0 {
			continue
		}
		if !reflect.DeepEqual(got, r.Tokens) {
			t.Errorf("command %q:\n  got  %#v\n  want %#v", r.Command, got, r.Tokens)
		}
	}
	if err := sc.Err(); err != nil {
		t.Fatalf("scan fixture: %v", err)
	}
	if n == 0 {
		t.Fatal("fixture file was empty")
	}
	t.Logf("checked %d shlex fixture rows", n)
}

func TestShlexQuote(t *testing.T) {
	cases := []struct{ in, want string }{
		{"", "''"},
		{"abc", "abc"},
		{"a-b_c.d/e:f,g=h@i%j+k", "a-b_c.d/e:f,g=h@i%j+k"},
		{"a b", "'a b'"},
		{"it's", `'it'"'"'s'`},
		{"{}", "'{}'"},
	}
	for _, c := range cases {
		if got := shlexQuote(c.in); got != c.want {
			t.Errorf("shlexQuote(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}
