// Code generated by clients/gen_help.py from the oracle's `daisugi help --all`. DO NOT EDIT.

package cli

// helpAll is the oracle's help --all text.
const helpAll = "" +
	"Start here:\n" +
	"  dashboard             The live 'factory floor': the module map with real...\n" +
	"  help                  Show the short start-here text, or every command with --all.\n" +
	"  start                 Get a gated session over this directory and watch it.\n" +
	"  status                Show day-one readiness: are token savings live and are...\n" +
	"\n" +
	"Run:\n" +
	"  orchestrate           Run PROMPT end to end: decompose → size → supervised...\n" +
	"\n" +
	"Gate:\n" +
	"  gate                  Call-time tool gate (ADR-0007) — verify each live tool...\n" +
	"    gate arm              Remove the disarm marker; the gate resumes...\n" +
	"    gate audit            Run the deterministic adversarial corpus and...\n" +
	"    gate check            Read one hook payload from stdin and emit the...\n" +
	"    gate disarm           Kill switch: the gate allows everything until...\n" +
	"    gate init             Generate and register a reviewable starter...\n" +
	"    gate proposals        List recorded envelope-edit proposals...\n" +
	"    gate register         Register the envelope the gate checks this...\n" +
	"    gate replay           Replay a captured session through the gate...\n" +
	"    gate report           Summarize the audit log: what an enforcing gate...\n" +
	"    gate serve            Run the resident gate in the foreground (Ctrl-C...\n" +
	"    gate settings         Print the Claude Code hooks-settings JSON that...\n" +
	"    gate status           Show armed/disarmed state, the verdict mode, and...\n" +
	"  install               Wire openDaisugi into every detected agent harness.\n" +
	"\n" +
	"Garden:\n" +
	"  journal               Inspect and replay journal traces.\n" +
	"    journal ingest           Ingest parsed episodes into the journal.\n" +
	"    journal parse            Parse an agent transcript into episodes.\n" +
	"    journal replay           Re-run verify() on a stored trace and report drift.\n" +
	"    journal search           Semantic search over journal traces (requires...\n" +
	"    journal stats            Print aggregate stats from the journal index.\n" +
	"  models               (hidden)  The models the garden can use: a curated list, a search,...\n" +
	"    models list             List the curated models, the default for this...\n" +
	"    models pin              Resolve a repo to a file pinned to its commit;...\n" +
	"    models search           Search the Hugging Face API for models, filtered...\n" +
	"    models use              Record the model the garden uses.\n" +
	"  pathways              Manage compiled pathways.\n" +
	"    pathways delete           Delete a compiled pathway.\n" +
	"    pathways export           Export a compiled pathway for sharing or inspection.\n" +
	"    pathways import           Import a pathway bundle, re-verify, and admit to...\n" +
	"    pathways list             List all compiled pathways.\n" +
	"    pathways show             Show a compiled pathway in detail.\n" +
	"    pathways stats            Summarize stored pathways (count, total hits).\n" +
	"\n" +
	"Settings:\n" +
	"  config                Show every setting as daisugi will use it, and where each...\n" +
	"\n" +
	"Other:\n" +
	"  batch                (hidden)  Within-instance batch compilation (roadmap Stage 9) —...\n" +
	"    batch prove            Statically prove a declared batch before any...\n" +
	"  bench                (hidden)  Compare the options within one layer over a small...\n" +
	"  conformance          (hidden)  Multi-client conformance corpus: export recorded cases,...\n" +
	"    conformance bench            Per-case latency percentiles over the corpus...\n" +
	"    conformance export           Dedupe recorded case lines into a sorted,...\n" +
	"    conformance run              Differential run: feed every case to a client,...\n" +
	"    conformance serve            Speak the wire protocol as the Python oracle:...\n" +
	"  coppice              (hidden)  Drive panes on the floor: spawn, read, prompt, wait,...\n" +
	"    coppice attach           Take over a pane full screen.\n" +
	"    coppice backends         Which pane backends this box has, and what to run...\n" +
	"    coppice close            Close a pane.\n" +
	"    coppice floor            Open the floor: the roster, a peek on one pane,...\n" +
	"    coppice herdr-bridge     Show a coppice pane in Herdr: write the manifest,...\n" +
	"    coppice list             Every pane, its label, its state, and where that...\n" +
	"    coppice prompt           Send a prompt.\n" +
	"    coppice read             Print what the pane shows.\n" +
	"    coppice send-keys        Send key presses to a pane.\n" +
	"    coppice spawn            Start a command in a new pane and print its id.\n" +
	"    coppice task             Tasks above panes: a name, a worktree, a parent,...\n" +
	"    coppice wait             Block until the pane reaches a state.\n" +
	"  distill-repeats      (hidden)  Rank repeated gateway asks into a reuse worklist — the...\n" +
	"  gardener             (hidden)  Lifecycle management for compiled pathways (prune, merge,...\n" +
	"    gardener merge            Collapse near-duplicate pathways.\n" +
	"    gardener prune            Evict stale / failure-dominated pathways.\n" +
	"    gardener run              Run the full gardener pipeline (prune + merge).\n" +
	"    gardener status           Report current store size, pathway activation...\n" +
	"    gardener watch            Cron-friendly one-shot gardener.\n" +
	"  gateway              (hidden)  Run the token-saving gateway: a local proxy any harness...\n" +
	"  gateway-report       (hidden)  Calibrate the gateway on a real recorded day: realized...\n" +
	"  generate-envelope    (hidden)  Generate a safety envelope for TASK via an LLM.\n" +
	"  graft                (hidden)  Install, show and remove the gate's graft rule for large...\n" +
	"    graft install          Write the large-read graft rule into...\n" +
	"    graft remove           Remove a graft rule file.\n" +
	"    graft status           Show the graft rule files, the one in force, and...\n" +
	"  hook                 (hidden)  Passive hook surface — capture tool calls into local...\n" +
	"    hook auto-tend        Close the captures→traces→distillation loop in...\n" +
	"    hook list             List captured sessions with call counts.\n" +
	"    hook record           Read a hook payload from stdin, record it, return...\n" +
	"    hook report           Read one PaneStateEvent JSON line from stdin and...\n" +
	"    hook to-trace         Convert a captured session into a journal trace.\n" +
	"  lora                 (hidden)  LoRA training-data pipeline (v0.5.0).\n" +
	"    lora export           Emit (task → envelope JSON) pairs from the...\n" +
	"    lora train            Train a LoRA adapter (python -m...\n" +
	"  mcp                  (hidden)  Run openDaisugi as an MCP server for Claude Code /...\n" +
	"    mcp serve            Serve openDaisugi tools over MCP stdio.\n" +
	"  metrics              (hidden)  Prometheus metrics: exposition text on stdout, or an HTTP...\n" +
	"  modules              (hidden)  Show the module wiring: what's active, available to swap...\n" +
	"  onboard              (hidden)  Turn existing conversations into token-saving pathways —...\n" +
	"  pack                 (hidden)  The ML packs: a pinned Python with locked packages, for...\n" +
	"    pack bundle           Fetch a pack's Python and wheels into OUT, for...\n" +
	"    pack install          Install a pack: the pinned Python, a virtual...\n" +
	"    pack list             List the packs and which are installed.\n" +
	"    pack remove           Delete a pack's directory, and nothing else.\n" +
	"    pack run              Run one job in a pack's worker.\n" +
	"    pack status           Check the installed packs against their pins.\n" +
	"  rank                 (hidden)  Rank N attempts at one task, record the choice, and...\n" +
	"    rank choose           Rank the attempts, take the leader, and open a...\n" +
	"    rank fit              Rank the attempts: eliminate, then quality, then...\n" +
	"    rank queue            List the open cards: what was chosen, why, and...\n" +
	"    rank record           Record the owner's answer on a card.\n" +
	"  registry             (hidden)  Git-backed shared pathway registry (v0.25+).\n" +
	"    registry init             Clone a registry repo to a local directory.\n" +
	"    registry publish          Sign + commit + push a local pathway as a bundle...\n" +
	"    registry pull             git pull and materialize new pathway bundles into...\n" +
	"    registry pull-and-tend    Cron-friendly: pull new bundles from the...\n" +
	"    registry status           Show the local clone's diagnostic info.\n" +
	"  release              (hidden)  Sign and verify release artifacts (roadmap Stage 7).\n" +
	"    release keygen           Generate an ed25519 release-signing keypair.\n" +
	"    release sign             Build a SHA-256 manifest over ARTIFACTS and sign it.\n" +
	"    release verify           Verify a release: trusted signature AND intact...\n" +
	"  route                (hidden)  Recommend the cheapest viable model/tier for a task.\n" +
	"  router               (hidden)  The gateway's model chooser: NVIDIA NeMo Switchyard as a...\n" +
	"    router label            Record whether a session's task succeeded: the...\n" +
	"    router status           Show the router choice, the Switchyard binary,...\n" +
	"    router stop             Stop every switchyard-server that a gateway...\n" +
	"  run                  (hidden)  Execute PLAN against ENVELOPE under runtime supervision.\n" +
	"  setup                (hidden)  Moved: `daisugi setup` is now `daisugi tiers setup` (same...\n" +
	"  tend                 (hidden)  Run the distiller.\n" +
	"  tiers                (hidden)  Tier-0/1/2 routing stats derived from the journal.\n" +
	"    tiers setup            Detect hardware, recommend a local model, and...\n" +
	"    tiers stats            Show per-tier call counts, estimated tokens, and...\n" +
	"  tree                 (hidden)  The delegation tree: prove each edge, keep the budgets,...\n" +
	"    tree answer           Answer an ask: allow starts the child as...\n" +
	"    tree check            Prove that the child's envelope fits inside the...\n" +
	"    tree end              Record that a node ended; its parent gets the...\n" +
	"    tree root             Make a root of the tree: the operator's envelope...\n" +
	"    tree spawn            Prove the edge, reserve the child's budget and...\n" +
	"    tree status           Show the tree: each node's state, budgets and...\n" +
	"  verify               (hidden)  Verify an action plan against a safety envelope.\n" +
	"  viz                  (hidden)  Render a distilled pathway's plan as a standalone...\n" +
	"  voice                (hidden)  The voice bridge.\n" +
	"    voice arm              Grant PANE direct send for a time window.\n" +
	"    voice disarm           Revoke PANE's direct-send grant.\n" +
	"    voice ptt              Laptop push-to-talk.\n" +
	"    voice serve            Run the voice bridge.\n" +
	"  weave                (hidden)  Run the plan tree in PLAN against ENVELOPE, with typed...\n" +
	"\n" +
	""
