"""Write schemas_gen.go: the texts the oracle's structured model calls
put in a request, taken from the oracle itself.

    uv run --no-sync python clients/go/internal/llm/gen_schemas.py [--check]

For each response model the oracle asks a model for (the distiller's
GeneralizedTemplate, Envelope, pathway_bind's Bindings, the decomposer's
DecomposedPlan, the synthesizer's _Answer, and each step type the
recompute fallback asks for):

- the JSON-mode system text the HTTP backend appends
  (llm_client.json_mode_system);
- the schema text the claude-code backend puts in its prompt
  (json.dumps(schema, indent=2)).

--check exits 1 when the file on disk is not what this would write (the
oracle's texts or the models changed).
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(REPO / "src"))
OUT = Path(__file__).resolve().parent / "schemas_gen.go"


def go_string(s: str) -> str:
    """A Go interpreted string literal for s (every byte kept)."""
    out = ['"']
    for ch in s:
        o = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif o < 0x20 or o == 0x7F:
            out.append(f"\\x{o:02x}")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def render() -> str:
    from opendaisugi.decomposer import DecomposedPlan
    from opendaisugi.distiller import GeneralizedTemplate
    from opendaisugi.llm_client import json_mode_system
    from opendaisugi.models import STEP_TYPE_REGISTRY, Envelope
    from opendaisugi.pathway_bind import Bindings
    from opendaisugi.synthesizer import _Answer

    lines = [
        "// Code generated by gen_schemas.py; DO NOT EDIT.",
        "",
        "package llm",
        "",
        "// jsonModeSystem is what the HTTP backend appends to the system",
        "// message, per response model (llm_client.json_mode_system).",
        "var jsonModeSystem = map[string]string{",
    ]
    models = {
        "GeneralizedTemplate": GeneralizedTemplate,
        "Envelope": Envelope,
        "Bindings": Bindings,
        "DecomposedPlan": DecomposedPlan,
        "_Answer": _Answer,
    }
    for cls in STEP_TYPE_REGISTRY.values():
        models[cls.__name__] = cls
    for name, m in models.items():
        lines.append(f"\t{go_string(name)}: {go_string(json_mode_system(m))},")
    lines += [
        "}",
        "",
        "// claudeSchema is the schema text the claude-code backend puts in its",
        "// prompt, per response model.",
        "var claudeSchema = map[string]string{",
    ]
    for name, m in models.items():
        lines.append(
            f"\t{go_string(name)}: {go_string(json.dumps(m.model_json_schema(), indent=2))},"
        )
    lines += ["}", ""]
    return "\n".join(lines)


def main() -> int:
    text = render()
    proc = subprocess.run(["gofmt"], input=text.encode(), capture_output=True, check=True)
    text = proc.stdout.decode()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print("schemas_gen.go is stale: run gen_schemas.py", file=sys.stderr)
            return 1
        print("schemas_gen.go is current")
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
