"""Write schemas_gen.go: the texts the oracle's structured model calls
put in a request, taken from the libraries themselves.

    uv run --no-sync python clients/go/internal/llm/gen_schemas.py [--check]

For each response model the distiller asks for (GeneralizedTemplate and
Envelope):

- the JSON-mode system text instructor appends (its schema dumped with
  ensure_ascii=False inside instructor's own dedented wrapper);
- the schema text the claude-code backend puts in its prompt
  (json.dumps(schema, indent=2)).

And litellm's max_tokens for each Anthropic model it knows by name; any
other name gets litellm's default. --check exits 1 when the file on disk
is not what this would write (the libraries or the models changed).
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(REPO / "src"))
OUT = Path(__file__).resolve().parent / "schemas_gen.go"


def go_string(s: str) -> str:
    """A Go interpreted string literal for s (every byte kept)."""
    out = ['"']
    for ch in s:
        o = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif o < 0x20 or o == 0x7F:
            out.append(f"\\x{o:02x}")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def instructor_suffix(model) -> str:
    from instructor.v2.providers.openai.handlers import OpenAIJSONHandler

    _, kw = OpenAIJSONHandler().prepare_request(model, {"messages": [{"role": "system", "content": "X"}]})
    text = kw["messages"][0]["content"]
    assert text.startswith("X\n\n"), text[:40]
    return text[3:]


def render() -> str:
    import litellm
    from litellm.llms.anthropic.chat.transformation import AnthropicConfig

    from opendaisugi.distiller import GeneralizedTemplate
    from opendaisugi.models import Envelope

    lines = [
        "// Code generated by gen_schemas.py; DO NOT EDIT.",
        "",
        "package llm",
        "",
        "// instructorSystem is what instructor's JSON mode appends to the system",
        "// message, per response model.",
        "var instructorSystem = map[string]string{",
    ]
    models = {"GeneralizedTemplate": GeneralizedTemplate, "Envelope": Envelope}
    for name, m in models.items():
        lines.append(f"\t{go_string(name)}: {go_string(instructor_suffix(m))},")
    lines += ["}", "", "// claudeSchema is the schema text the claude-code backend puts in its", "// prompt, per response model.", "var claudeSchema = map[string]string{"]
    for name, m in models.items():
        lines.append(f"\t{go_string(name)}: {go_string(json.dumps(m.model_json_schema(), indent=2))},")
    lines += ["}", "", "// anthropicMaxTokens is litellm's max_tokens for each Anthropic model it", "// knows by name; any other name gets defaultMaxTokens.", "var anthropicMaxTokens = map[string]int{"]
    names = sorted(k for k, v in litellm.model_cost.items() if v.get("litellm_provider") == "anthropic")
    for k in names:
        lines.append(f"\t{go_string(k)}: {AnthropicConfig.get_max_tokens_for_model(k)},")
    lines += ["}", "", f"// defaultMaxTokens is litellm's DEFAULT_ANTHROPIC_CHAT_MAX_TOKENS.",
              f"const defaultMaxTokens = {AnthropicConfig.get_max_tokens_for_model(None)}", ""]
    return "\n".join(lines)


def main() -> int:
    text = render()
    proc = subprocess.run(["gofmt"], input=text.encode(), capture_output=True, check=True)
    text = proc.stdout.decode()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print("schemas_gen.go is stale: run gen_schemas.py", file=sys.stderr)
            return 1
        print("schemas_gen.go is current")
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
