"""Write the system dialect's tables for the Go and Rust clients.

    uv run --no-sync python clients/gen_dialect.py [--check]

The oracle's ``opendaisugi.dialect`` holds the words: their parameters,
bodies and synonyms, the canonical JSON the dialect hash is taken over,
and the prefix of an audit warning; ``opendaisugi.write_paths`` holds the
commands whose operands are write paths, with their flag sets. This
writes them, as the oracle holds them, to ``clients/go/internal/verify/dialect_gen.go`` and
``clients/rust/src/dialect_gen.rs``. The glob translation is logic, not a
table: each client ports ``glob_regex`` by hand and tests it against
``clients/fixtures/dialect/globs.json``. With ``--check`` nothing is
written, and the exit code is 1 when a file is stale.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from opendaisugi import dialect, write_paths

REPO = Path(__file__).resolve().parent.parent
GO_OUT = REPO / "clients" / "go" / "internal" / "verify" / "dialect_gen.go"
RUST_OUT = REPO / "clients" / "rust" / "src" / "dialect_gen.rs"


def _go_str(s: str) -> str:
    return json.dumps(s, ensure_ascii=True)


def _rust_str(s: str) -> str:
    return json.dumps(s, ensure_ascii=True)


def _body(word: str) -> str:
    return json.dumps(dialect.WORDS[word]["body"], sort_keys=True, separators=(",", ":"))


def go_source() -> str:
    lines = [
        "// Code generated by clients/gen_dialect.py from opendaisugi.dialect. DO NOT EDIT.",
        "",
        "package verify",
        "",
        "// DialectJSON is dialect.DIALECT_JSON: the canonical JSON the hash is taken over.",
        f"const DialectJSON = {_go_str(dialect.DIALECT_JSON)}",
        "",
        "// DialectHash is dialect.DIALECT_HASH.",
        f"const DialectHash = {_go_str(dialect.DIALECT_HASH)}",
        "",
        "// DialectAuditPrefix is dialect.AUDIT_PREFIX.",
        f"const DialectAuditPrefix = {_go_str(dialect.AUDIT_PREFIX)}",
        "",
        "// The limits of a supported target glob (dialect.MAX_GLOB_*).",
        "const (",
        f"\tmaxGlobChars       = {dialect.MAX_GLOB_CHARS}",
        f"\tmaxGlobDoubleStars = {dialect.MAX_GLOB_DOUBLE_STARS}",
        f"\tmaxGlobStars       = {dialect.MAX_GLOB_STARS}",
        ")",
        "",
        "// dialectWord is one word of dialect.WORDS: its one glob parameter and body.",
        "type dialectWord struct {",
        "\tParam, Default, Body string",
        "}",
        "",
        "// dialectWords is dialect.WORDS.",
        "var dialectWords = map[string]dialectWord{",
    ]
    for word, spec in sorted(dialect.WORDS.items()):
        (param,) = spec["params"]
        assert param["sort"] == "glob"
        lines.append(
            f"\t{_go_str(word)}: {{Param: {_go_str(param['name'])}, "
            f"Default: {_go_str(param['default'])}, Body: {_go_str(_body(word))}}},"
        )
    lines += [
        "}",
        "",
        "// dialectSynonyms is dialect.SYNONYMS.",
        "var dialectSynonyms = map[string]string{",
    ]
    width = max(len(_go_str(n)) for n in dialect.SYNONYMS) + 1
    for name, word in sorted(dialect.SYNONYMS.items()):
        lines.append(f"\t{(_go_str(name) + ':').ljust(width)} {_go_str(word)},")
    lines += [
        "}",
        "",
        "// writerSpec is one command of write_paths.WRITERS: its rule and the",
        "// closed flag sets it may carry.",
        "type writerSpec struct {",
        "\tName, Rule, Short, ShortValue, ShortOptional string",
        "\tLong, LongValue, LongOptional                []string",
        "}",
        "",
        "// writerList is write_paths.WRITERS, by name.",
        "var writerList = []writerSpec{",
    ]
    for name, spec in sorted(write_paths.WRITERS.items()):
        fields = [f"Name: {_go_str(name)}", f"Rule: {_go_str(spec['rule'])}"]
        for key, go in (("short", "Short"), ("short_value", "ShortValue")):
            if spec.get(key):
                fields.append(f"{go}: {_go_str(spec[key])}")
        if spec.get("short_optional"):
            fields.append(f"ShortOptional: {_go_str(spec['short_optional'])}")
        for key, go in (("long", "Long"), ("long_value", "LongValue")):
            if spec.get(key):
                fields.append(f"{go}: []string{{{', '.join(_go_str(f) for f in spec[key])}}}")
        if spec.get("long_optional"):
            opts = ", ".join(_go_str(f) for f in spec["long_optional"])
            fields.append(f"LongOptional: []string{{{opts}}}")
        lines.append(f"\t{{{', '.join(fields)}}},")
    keys = ", ".join(_go_str(k) for k in sorted(write_paths.DD_KEYS))
    lines += [
        "}",
        "",
        "// ddKeyList is write_paths.DD_KEYS.",
        f"var ddKeyList = []string{{{keys}}}",
        "",
    ]
    return "\n".join(lines)


def rust_source() -> str:
    lines = [
        "// Code generated by clients/gen_dialect.py from opendaisugi.dialect. DO NOT EDIT.",
        "",
        "/// `dialect.DIALECT_JSON`: the canonical JSON the hash is taken over.",
        f"pub const DIALECT_JSON: &str = {_rust_str(dialect.DIALECT_JSON)};",
        "",
        "/// `dialect.DIALECT_HASH`.",
        f"pub const DIALECT_HASH: &str = {_rust_str(dialect.DIALECT_HASH)};",
        "",
        "/// `dialect.AUDIT_PREFIX`.",
        f"pub const AUDIT_PREFIX: &str = {_rust_str(dialect.AUDIT_PREFIX)};",
        "",
        "/// `dialect.MAX_GLOB_CHARS`.",
        f"pub const MAX_GLOB_CHARS: usize = {dialect.MAX_GLOB_CHARS};",
        "/// `dialect.MAX_GLOB_DOUBLE_STARS`.",
        f"pub const MAX_GLOB_DOUBLE_STARS: usize = {dialect.MAX_GLOB_DOUBLE_STARS};",
        "/// `dialect.MAX_GLOB_STARS`.",
        f"pub const MAX_GLOB_STARS: usize = {dialect.MAX_GLOB_STARS};",
        "",
        "/// `dialect.WORDS`: (word, glob parameter, its default, body JSON).",
        "pub const WORDS: &[(&str, &str, &str, &str)] = &[",
    ]
    for word, spec in sorted(dialect.WORDS.items()):
        (param,) = spec["params"]
        assert param["sort"] == "glob"
        lines.append(
            f"    ({_rust_str(word)}, {_rust_str(param['name'])}, "
            f"{_rust_str(param['default'])}, {_rust_str(_body(word))}),"
        )
    lines += [
        "];",
        "",
        "/// `dialect.SYNONYMS`: (type name, word).",
        "pub const SYNONYMS: &[(&str, &str)] = &[",
    ]
    for name, word in sorted(dialect.SYNONYMS.items()):
        lines.append(f"    ({_rust_str(name)}, {_rust_str(word)}),")
    lines += [
        "];",
        "",
        "/// One command of `write_paths.WRITERS`: its rule and the closed flag",
        "/// sets it may carry.",
        "pub struct WriterSpec {",
        "    pub rule: &'static str,",
        "    pub short: &'static str,",
        "    pub short_value: &'static str,",
        "    pub short_optional: &'static str,",
        "    pub long: &'static [&'static str],",
        "    pub long_value: &'static [&'static str],",
        "    pub long_optional: &'static [&'static str],",
        "}",
        "",
        "/// `write_paths.WRITERS`, by command name.",
        "pub const WRITERS: &[(&str, WriterSpec)] = &[",
    ]
    for name, spec in sorted(write_paths.WRITERS.items()):

        def lst(key: str, spec: dict = spec) -> str:
            return "&[" + ", ".join(_rust_str(f) for f in spec.get(key, [])) + "]"

        lines += [
            f"    ({_rust_str(name)}, WriterSpec {{",
            f"        rule: {_rust_str(spec['rule'])},",
            f"        short: {_rust_str(spec.get('short', ''))},",
            f"        short_value: {_rust_str(spec.get('short_value', ''))},",
            f"        short_optional: {_rust_str(spec.get('short_optional', ''))},",
            f"        long: {lst('long')},",
            f"        long_value: {lst('long_value')},",
            f"        long_optional: {lst('long_optional')},",
            "    }),",
        ]
    lines += [
        "];",
        "",
        "/// `write_paths.DD_KEYS`.",
        "pub const DD_KEYS: &[&str] = &[",
    ]
    for key in sorted(write_paths.DD_KEYS):
        lines.append(f"    {_rust_str(key)},")
    lines += ["];", ""]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    check = "--check" in argv
    stale = []
    for path, text in ((GO_OUT, go_source()), (RUST_OUT, rust_source())):
        if check:
            if not path.exists() or path.read_text() != text:
                stale.append(path)
        else:
            path.write_text(text)
    for path in stale:
        print(f"{path.relative_to(REPO)} is stale: run clients/gen_dialect.py", file=sys.stderr)
    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
