"""Write the oracle's `daisugi help --all` text for the Go and Rust clients.

    uv run --no-sync python clients/gen_help.py [--check]

`daisugi help --all` lists every command of the Python CLI, grouped,
with its short help. Each port prints this text with the lines of the
commands it does not carry left out (`HELP_NOT_PORTED` in each port, the
same list as `clients/cli_cases.py`). This writes the oracle's text, as
the oracle prints it, to ``clients/go/internal/cli/helpall_gen.go`` and
``clients/rust/src/cli/helpall_gen.rs``. With ``--check`` nothing is
written, and the exit code is 1 when a file is stale.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
GO_OUT = REPO / "clients" / "go" / "internal" / "cli" / "helpall_gen.go"
RUST_OUT = REPO / "clients" / "rust" / "src" / "cli" / "helpall_gen.rs"

HEADER = (
    "Code generated by clients/gen_help.py from the oracle's `daisugi help --all`. DO NOT EDIT."
)


def oracle_text() -> str:
    env = {
        "HOME": os.environ.get("HOME", "/nonexistent"),
        "PATH": "/usr/bin:/bin",
        "PYTHONPATH": str(REPO / "src"),
        "LANG": "C.UTF-8",
        "NO_COLOR": "1",
        "COLUMNS": "100",
    }
    out = subprocess.run(  # noqa: S603 - the oracle CLI
        [sys.executable, "-m", "opendaisugi.cli", "help", "--all"],
        capture_output=True,
        env=env,
        check=True,
    )
    return out.stdout.decode("utf-8")


def go_source(text: str) -> str:
    lines = "".join(
        f"\t{json.dumps(ln + chr(10), ensure_ascii=False)} +\n" for ln in text.split("\n")[:-1]
    )
    return f'// {HEADER}\n\npackage cli\n\n// helpAll is the oracle\'s help --all text.\nconst helpAll = "" +\n{lines}\t""\n'


def rust_source(text: str) -> str:
    body = json.dumps(text, ensure_ascii=False)
    # A JSON string literal is a Rust string literal for the escapes it
    # uses (\n, \", \\) except \u00XX for a control character, which
    # Rust writes \u{XXXX}.
    body = re.sub(r"\\u([0-9a-fA-F]{4})", r"\\u{\1}", body)
    return f"// {HEADER}\n\n/// The oracle's help --all text.\npub const HELP_ALL: &str = {body};\n"


def main() -> int:
    check = "--check" in sys.argv[1:]
    text = oracle_text()
    stale = []
    for path, src in ((GO_OUT, go_source(text)), (RUST_OUT, rust_source(text))):
        if path.exists() and path.read_text(encoding="utf-8") == src:
            continue
        stale.append(path)
        if not check:
            path.write_text(src, encoding="utf-8")
    if check and stale:
        for p in stale:
            print(f"stale: {p.relative_to(REPO)}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
