// Code generated by gen_argparse.py. DO NOT EDIT.

package gate

// helpChunks are textwrap's chunks of each option's help, by its first
// option string, after argparse collapses the whitespace.
var helpChunks = map[string][]string{
	"-h":            {"show", " ", "this", " ", "help", " ", "message", " ", "and", " ", "exit"},
	"--session":     {"Pin", " ", "the", " ", "envelope", " ", "to", " ", "this", " ", "registered", " ", "session,", " ", "ignoring", " ", "the", " ", "session", " ", "id", " ", "in", " ", "the", " ", "payload", " ", "(authorization", " ", "must", " ", "not", " ", "key", " ", "on", " ", "caller-", "influenceable", " ", "input)."},
	"--ask":         {"Enforce", " ", "mode", " ", "only:", " ", "hand", " ", "a", " ", "would-", "deny", " ", "to", " ", "a", " ", "present", " ", "operator", " ", "for", " ", "up", " ", "to", " ", "--ask-", "timeout", " ", "seconds", " ", "before", " ", "letting", " ", "the", " ", "deny", " ", "stand.", " ", "Off", " ", "by", " ", "default."},
	"--checkpoints": {"Snapshot", " ", "the", " ", "workspace", " ", "into", " ", "a", " ", "private", " ", "git", " ", "ref", " ", "at", " ", "most", " ", "once", " ", "per", " ", "new", " ", "prompt", " ", "boundary.", " ", "Off", " ", "by", " ", "default;", " ", "best-", "effort", " ", "and", " ", "never", " ", "affects", " ", "the", " ", "verdict."},
}
