"""Write llm_gen.go: what the gate's llm_check port copies from litellm.

    python gen_llm.py

litellm redacts secrets from a provider's error text before it words the
exception (litellm_core_utils.secret_redaction._SECRET_RE). The port runs
the same pattern on pyre. Run with MINIMUM_CUSTOM_KEY_LENGTH unset, as the
gate refuses to decide a call when it is set.
"""

import importlib.metadata
import json
import os
import subprocess
from pathlib import Path

os.environ.pop("MINIMUM_CUSTOM_KEY_LENGTH", None)
from litellm.litellm_core_utils.secret_redaction import _SECRET_RE  # noqa: E402

version = importlib.metadata.version("litellm")
out = [
    f"// Code generated by gen_llm.py from litellm {version}. DO NOT EDIT.",
    "",
    "package gate",
    "",
    "// litellmVersion is the litellm the oracle's llm_check runs.",
    f'const litellmVersion = "{version}"',
    "",
    "// litellmSecretPattern and litellmSecretFlags are secret_redaction._SECRET_RE.",
    f"const litellmSecretPattern = {json.dumps(_SECRET_RE.pattern)}",
    "",
    f"const litellmSecretFlags = {int(_SECRET_RE.flags)}",
]
target = Path(__file__).with_name("llm_gen.go")
target.write_text("\n".join(out) + "\n", encoding="utf-8")
subprocess.run(["gofmt", "-w", str(target)], check=True)
print(version, len(_SECRET_RE.pattern))
