"""Write patterns_gen.go: every regex the oracle's gate path runs, as the
Python source spells it, so the port matches with the very same patterns.

    PYTHONPATH=src python clients/go/internal/gate/gen_patterns.py

A compiled module-level pattern is named module.NAME; a pattern written
inline in a call is named module.function#n, n counting from 0 in source
order.
"""

import ast
import importlib
import inspect
import re
import subprocess
from pathlib import Path

MODULES = [
    "opendaisugi.pane_rule",
    "opendaisugi.search_rule",
    "opendaisugi.floor_config",
    "opendaisugi.effects",
    "opendaisugi.verify",
    "opendaisugi.hook",
    "opendaisugi.session_tree",
    "opendaisugi.config",
]
RE_FUNCS = {"compile", "search", "match", "fullmatch", "sub", "subn", "findall", "finditer", "split"}


def const_eval(node, env):
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    if isinstance(node, ast.BinOp) and isinstance(node.op, ast.Add):
        a, b = const_eval(node.left, env), const_eval(node.right, env)
        if a is not None and b is not None:
            return a + b
    if isinstance(node, ast.Name) and isinstance(env.get(node.id), str):
        return env[node.id]
    if isinstance(node, ast.JoinedStr):
        return None
    return None


def main() -> None:
    out: dict[str, tuple[str, int]] = {}
    for modname in MODULES:
        mod = importlib.import_module(modname)
        short = modname.split(".")[-1]
        for name, val in vars(mod).items():
            if isinstance(val, re.Pattern):
                out[f"{short}.{name}"] = (val.pattern, int(val.flags))
        tree = ast.parse(inspect.getsource(mod))
        env = vars(mod)
        for fn in ast.walk(tree):
            if not isinstance(fn, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            n = 0
            for node in ast.walk(fn):
                if (isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute)
                        and isinstance(node.func.value, ast.Name) and node.func.value.id == "re"
                        and node.func.attr in RE_FUNCS and node.args):
                    pat = const_eval(node.args[0], env)
                    if pat is None:
                        continue
                    flags = 0
                    for kw in node.keywords:
                        if kw.arg == "flags":
                            flags = eval(compile(ast.Expression(kw.value), "<flags>", "eval"), env)
                    out[f"{short}.{fn.name}#{n}"] = (pat, int(flags))
                    n += 1
    lines = [
        "// Code generated by gen_patterns.py from the oracle's source. DO NOT EDIT.",
        "",
        "package gate",
        "",
        "// pyPatterns holds every regex the oracle's gate path runs: the pattern",
        "// and its flags, keyed by module.NAME or module.function#n.",
        "var pyPatterns = map[string]pyPattern{",
    ]
    for key in sorted(out):
        pat, flags = out[key]
        lines.append(f"\t{go_quote(key)}: {{{go_quote(pat)}, {int(flags)}}},")
    lines.append("}")
    target = Path(__file__).with_name("patterns_gen.go")
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    subprocess.run(["gofmt", "-w", str(target)], check=True)
    print(len(out), "patterns")


def go_quote(s: str) -> str:
    out = ['"']
    for ch in s:
        c = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif c < 0x20 or c == 0x7F:
            out.append("\\x%02x" % c)
        elif c < 0x80:
            out.append(ch)
        else:
            out.append("\\U%08x" % c)
    out.append('"')
    return "".join(out)


if __name__ == "__main__":
    main()
