"""Write argparse_gen.go: the help text chunks of gate._build_parser.

    python gen_argparse.py

argparse wraps each help string with textwrap.wrap. textwrap first splits
the text into chunks (words, hyphen pieces, spaces) with its wordsep_re,
which does not depend on the width, then fills lines from the chunks. The
chunks are computed here, by textwrap itself; argparse.go does the fill.
"""

import json
import re
import subprocess
import textwrap
from pathlib import Path

from opendaisugi.gate import _build_parser

p = _build_parser()
ws = re.compile(r"\s+", re.ASCII)
out = [
    "// Code generated by gen_argparse.py. DO NOT EDIT.",
    "",
    "package gate",
    "",
    "// helpChunks are textwrap's chunks of each option's help, by its first",
    "// option string, after argparse collapses the whitespace.",
    "var helpChunks = map[string][]string{",
]
for a in p._actions:
    if not a.help:
        continue
    text = ws.sub(" ", a.help % {"prog": p.prog}).strip()
    chunks = textwrap.TextWrapper()._split_chunks(text)
    out.append(f"\t{json.dumps(a.option_strings[0])}: {{" + ", ".join(json.dumps(c) for c in chunks) + "},")
out.append("}")
target = Path(__file__).with_name("argparse_gen.go")
target.write_text("\n".join(out) + "\n", encoding="utf-8")
subprocess.run(["gofmt", "-w", str(target)], check=True)
