// Code generated by gen_llm.py from litellm 1.100.0. DO NOT EDIT.

package gate

// litellmVersion is the litellm the oracle's llm_check runs.
const litellmVersion = "1.100.0"

// litellmSecretPattern and litellmSecretFlags are secret_redaction._SECRET_RE.
const litellmSecretPattern = "-----BEGIN[A-Z \\-]*PRIVATE KEY-----[\\s\\S]*?-----END[A-Z \\-]*PRIVATE KEY-----|\\bya29\\.[A-Za-z0-9_.~+/-]+|(?:client_secret|azure_password|azure_username)\\s+[^\\s,'\\\"})\\]{}>]+|(?:AKIA|ASIA)[0-9A-Z]{16}|Bearer\\s+[A-Za-z0-9\\-._~+/]{10,}=*|Basic\\s+[A-Za-z0-9+/]{10,}={0,2}|sk-[A-Za-z0-9\\-_]{13,}|(?:api[_-]?key)['\\\"]?\\s*[:=]\\s*['\\\"]?[^\\s,'\\\"})\\]{}>]{8,}|(?:x-api-key|api-key)['\\\"]?\\s*[:=]\\s*['\\\"]?[^\\s,'\\\"})\\]{}>]+|x-ak-[A-Za-z0-9\\-_]{20,}|AIza[0-9A-Za-z\\-_]{35}|(?<=[?&])key=[^\\s&'\\\"]{8,}|(?:^|(?<=\\W))\\w*(?:password|passwd|client_secret|secret_key|_secret)['\\\"]?\\s*[:=]\\s*['\\\"]?[^\\s,'\\\"})\\]{}>]+|(?<=://)[^\\s'\\\"]*:[^\\s'\\\"@]+(?=@)|dapi[0-9a-f]{32}|litellm\\.[A-Za-z0-9_]*_key['\\\"]?\\s*[:=]\\s*['\\\"]?[^\\s,'\\\"})\\]{}>]+|private_key['\\\"]?\\s*[:=]\\s*['\\\"]?(?:-----BEGIN[A-Z \\-]*PRIVATE KEY-----[\\s\\S]*?-----END[A-Z \\-]*PRIVATE KEY-----|[^\\s,'\\\"})\\]{}>]+)|(?:master_key|xai_key|database_url|db_url|connection_string|aws_secret_access_key|aws_session_token|aws_access_key_id|signing_key|encryption_key|auth_token|access_token|refresh_token|slack_webhook_url|webhook_url|database_connection_string|huggingface_token|jwt_secret)['\\\"]?\\s*[:=]\\s*['\\\"]?[^\\s,'\\\"})\\]{}>]+|\\beyJ[A-Za-z0-9_-]{10,}\\.[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]*|[?&]sig=[A-Za-z0-9%+/=]+|\\{[^{}]*\"type\"\\s*:\\s*\"service_account\"[^{}]*(?:\\{[^{}]*\\}[^{}]*)*\\}"

const litellmSecretFlags = 34
