// Code generated by gen_patterns.py from the oracle's source. DO NOT EDIT.

package gate

// pyPatterns holds every regex the oracle's gate path runs: the pattern
// and its flags, keyed by module.NAME or module.function#n.
var pyPatterns = map[string]pyPattern{
	"config._ASSIGNMENT":             {"^[A-Za-z_][A-Za-z0-9_]*=", 32},
	"config._JOINED_MODULE":          {"^-[A-Za-z]*m(opendaisugi\\.gate(_client)?)$", 32},
	"config._PYTHON":                 {"^(python[0-9.]*|py)$", 32},
	"effects._JQ_ENV":                {"(?<![\\w$])env(?!\\w)|\\$ENV(?!\\w)", 32},
	"floor_config._OPENCODE_TEXT":    {"(^|[^\\w.-])\\.opencode(/+(plugins?|tools?)(\\b|/)|/*(?=$|[\\s'\\\"`;&|)]))|\\bopencode\\.jsonc?\\b", 32},
	"floor_config._VARS":             {"\\$\\{(HOME|XDG_CONFIG_HOME|XDG_DATA_HOME|COPPICE_DATA_DIR|OPENDAISUGI_HOME)(?:[^A-Za-z0-9_}][^}]*)?\\}|\\$(HOME|XDG_CONFIG_HOME|XDG_DATA_HOME|COPPICE_DATA_DIR|OPENDAISUGI_HOME)\\b", 32},
	"hook._PATCH_HEREDOC":            {"^(?:cat\\s+)?<<['\\\"]?(\\w+)['\\\"]?\\s*\\n([\\s\\S]*?)\\n\\1\\s*$", 32},
	"hook._safe_session_id#0":        {"[^A-Za-z0-9._-]", 0},
	"hook.infer_envelope#0":          {"https?://([^/]+)", 0},
	"pane_rule._ALLOW_TEXT":          {"\\bcoppice\\b[^\\n;&|]*?\\bagent\\b[\\s'\\\"]+(allow)\\b", 32},
	"pane_rule._ASK_PATH_TEXT":       {"(^|[\\s'\\\"=:(/])gate/(asks|answers)\\b", 32},
	"pane_rule._CHAT_WIRE_TEXT":      {"['\\\"]?(cmd|method)\\\\?['\\\"]?\\s*[:=]\\s*\\\\?['\\\"](floor\\.chat|pane\\.messages)\\\\?['\\\"]", 32},
	"pane_rule._DENY_TEXT":           {"\\bcoppice\\b[^\\n;&|]*?\\bagent\\b[\\s'\\\"]+deny\\b|['\\\"]?(cmd|method)\\\\?['\\\"]?\\s*[:=]\\s*\\\\?['\\\"]agent\\.deny\\\\?['\\\"]|['\\\"]agent['\\\"]\\s*,\\s*['\\\"]deny['\\\"]", 32},
	"pane_rule._OTHER_SERVER":        {"(^|[\\s'\\\"])--(remote|socket)(=|[\\s'\\\"]|$)|\\bXDG_RUNTIME_DIR\\b|\\bHOME=|\\bOPENDAISUGI_HOME=|\\bXDG_DATA_HOME=", 32},
	"pane_rule._PRIVATE_DIR_TEXT":    {"opendaisugi/coppice/(chat|journal)($|[/ \\t\\n\\r'\\\"`;&|)])", 32},
	"pane_rule._SECRET_FILE":         {"(^|[^A-Za-z0-9_])(web/token|web/ca/ca\\.key|web/ca/leaf\\.key|web/tls/tailscale\\.key|voice/token|chat/[0-9]{4}-[0-9]{2}-[0-9]{2}\\.jsonl|journal/verdicts\\.jsonl)\\b", 32},
	"pane_rule._WEB_TOKEN_CMD":       {"\\bcoppice\\b[^\\n;&|]*?\\bweb\\b[\\s'\\\"]+token\\b", 32},
	"pane_rule._WIRE_TEXT":           {"['\\\"]?(cmd|method)\\\\?['\\\"]?\\s*[:=]\\s*\\\\?['\\\"]agent\\.(allow)\\\\?['\\\"]|['\\\"]agent['\\\"]\\s*,\\s*['\\\"](allow)['\\\"]", 32},
	"pane_rule._WRAPPER_ANYWHERE":    {"\\b(ssh|setsid|systemd-run|nohup|tmux|daemonize|start-stop-daemon|start_new_session)\\b", 32},
	"pane_rule._WRAPPER_HEAD":        {"(?:^|[\\n;&|(){}`'\\\"!])\\s*(?:\\w+=\\S*\\s+)*(?:(?:\\S*/)?(?:env|exec|command|builtin|nice|time|stdbuf|ionice|chrt|taskset|timeout)\\b[^\\n;&|]*?\\s)?(?:\\S*/)?(?:ssh|mosh|setsid|systemd-run|nohup|at|batch|tmux|screen|dtach|abduco|zellij|byobu|script|unbuffer|expect|daemonize|start-stop-daemon|sudo|doas|pkexec|su|runuser|machinectl|crontab|flatpak-spawn|distrobox-host-exec)(?:$|[\\s;&|)'\\\"`])", 32},
	"pane_rule._home_spellings#0":    {"(^|[\\s'\\\"=:(])~(?=/)", 0},
	"pane_rule.shell_touches_asks#0": {"\\b(asks|answers)\\b", 0},
	"search_rule._ASSIGN":            {"[A-Za-z_][A-Za-z0-9_]*=", 32},
	"search_rule._BRACE":             {"\\{([^{}]*)\\}", 32},
	"search_rule._GLOB":              {"[*?\\[{]", 32},
	"search_rule._PROGRAM_TEXT":      {"(^|[^A-Za-z0-9_.-])(rg|ag|ack|rgrep|ugrep|ug|grep|egrep|fgrep|zgrep|find)($|[^A-Za-z0-9_.-])", 32},
	"search_rule._SEQ":               {"(-?[0-9]+|[A-Za-z])\\.\\.(-?[0-9]+|[A-Za-z])(\\.\\.(-?[0-9]+))?", 32},
	"search_rule._UNRESOLVED":        {"\\$[A-Za-z_{(0-9@*#?!$-]|`", 32},
	"search_rule._find_roots#0":      {"-O[0-9]*", 0},
	"search_rule._grep_recurses#0":   {"-[0-9]+", 0},
	"session_tree._safe_id#0":        {"[^A-Za-z0-9._-]", 0},
	"verify._ENV_ASSIGN_RE":          {"^[A-Za-z_][A-Za-z0-9_]*=", 32},
	"verify._GLOB_CHARS_RE":          {"[*?\\[]", 32},
	"verify._SHELL_METACHAR_RE":      {"[;|&`<>\\n\\r]|\\$\\(", 32},
	"verify._Z3_TIMEOUT_WARNING_RE":  {"^Z3 .* exceeded -?\\d+ms$", 32},
}
