"""Write tables_gen.go: what the tokenizers library's BertNormalizer and
BertPreTokenizer do to each code point.

    uv run --no-sync python clients/go/internal/embed/potion/gen_tables.py

The tables come from the library itself, not from Go's unicode package,
so they hold the library's own Unicode version. The normalizer config is
the one model2vec's potion models use: clean_text, handle_chinese_chars,
strip_accents unset (so it follows lowercase) and lowercase.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import tokenizers
from tokenizers import normalizers, pre_tokenizers

OUT = Path(__file__).resolve().parent / "tables_gen.go"


def ranges(cps: list[int]) -> list[tuple[int, int]]:
    out: list[list[int]] = []
    for c in cps:
        if out and out[-1][1] == c - 1:
            out[-1][1] = c
        else:
            out.append([c, c])
    return [(a, b) for a, b in out]


def hangul(c: int) -> str | None:
    """The NFD of a Hangul syllable, computed, so the table need not list them."""
    s = c - 0xAC00
    if not 0 <= s < 11172:
        return None
    lead, vowel, tail = 0x1100 + s // 588, 0x1161 + (s % 588) // 28, 0x11A7 + s % 28
    return chr(lead) + chr(vowel) + (chr(tail) if tail != 0x11A7 else "")


def main() -> None:
    norm = normalizers.BertNormalizer(
        clean_text=True, handle_chinese_chars=True, strip_accents=None, lowercase=True
    )
    pre = pre_tokenizers.BertPreTokenizer()
    removed, space, cjk, ws, punct = [], [], [], [], []
    mapped: list[tuple[int, str]] = []
    for c in range(0x110000):
        if 0xD800 <= c <= 0xDFFF:
            continue
        ch = chr(c)
        r = norm.normalize_str(ch)
        if r != ch:
            if r == "":
                removed.append(c)
            elif r == " ":
                space.append(c)
            elif r == f" {ch} ":
                cjk.append(c)
            elif r != hangul(c):
                mapped.append((c, r))
        parts = pre.pre_tokenize_str("a" + ch + "b")
        if len(parts) == 2:
            ws.append(c)
        elif len(parts) == 3:
            punct.append(c)
    lines = [
        "// Code generated by gen_tables.py from tokenizers "
        + tokenizers.__version__
        + ". DO NOT EDIT.",
        "",
        "package potion",
        "",
    ]

    def table(name: str, doc: str, cps: list[int]) -> None:
        lines.append(f"// {name} {doc}")
        lines.append(f"var {name} = []rng{{")
        row = []
        for a, b in ranges(cps):
            row.append(f"{{0x{a:X}, 0x{b:X}}},")
            if len(row) == 6:
                lines.append("\t" + " ".join(row))
                row = []
        if row:
            lines.append("\t" + " ".join(row))
        lines.append("}")
        lines.append("")

    table("normRemoved", "are dropped by clean_text.", removed)
    table("normSpace", "become one space.", space)
    table("normCJK", "get a space on each side.", cjk)
    table("preSpace", "split words and are dropped (on normalized text).", ws)
    table("prePunct", "are words of their own.", punct)
    lines.append("// normMapped is every other code point the normalizer changes: accents")
    lines.append("// stripped and lowercased, sorted by code point. Hangul syllables are")
    lines.append("// decomposed in code. A slice, not a map, so a start of the binary")
    lines.append("// builds nothing.")
    lines.append("var normMapped = []mapped{")
    for c, r in mapped:
        lines.append(f"\t{{0x{c:X}, {go_str(r)}}},")
    lines.append("}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    subprocess.run(["gofmt", "-w", str(OUT)], check=True)
    print(f"wrote {OUT.name}: {len(mapped)} mapped, {len(removed)} removed, {len(punct)} punctuation")


def go_str(s: str) -> str:
    return '"' + "".join(f"\\u{ord(c):04X}" if ord(c) < 0x10000 else f"\\U{ord(c):08X}" for c in s) + '"'


if __name__ == "__main__":
    main()
