"""Write case_gen.go: str.lower() and str.casefold() of every code point
they change, from the Python the oracle runs (Unicode 15.0.0).

    python clients/go/internal/pystr/gen_tables.py
"""

import subprocess
import sys
import unicodedata
from pathlib import Path


def go_str(s: str) -> str:
    return '"' + "".join("\\U%08x" % ord(c) for c in s) + '"'


def table(name: str, fn) -> list[str]:
    lines = [f"var {name} = map[rune]string{{"]
    for cp in range(sys.maxunicode + 1):
        c = chr(cp)
        if 0xD800 <= cp <= 0xDFFF:
            continue
        v = fn(c)
        if v != c:
            lines.append(f"\t0x{cp:x}: {go_str(v)},")
    lines.append("}")
    return lines


def ranges(name: str, pred) -> list[str]:
    lines = [f"var {name} = []runeRange{{"]
    start = None
    for cp in range(sys.maxunicode + 2):
        ok = cp <= sys.maxunicode and not 0xD800 <= cp <= 0xDFFF and pred(chr(cp))
        if ok and start is None:
            start = cp
        elif not ok and start is not None:
            lines.append(f"\t{{0x{start:x}, 0x{cp - 1:x}}},")
            start = None
    lines.append("}")
    return lines


def sigma(prefix: str, c: str) -> bool:
    return (prefix + c + "Σ").lower().endswith("ς")


def main() -> None:
    # str.lower() writes a final sigma after a cased letter, skipping
    # case-ignorable ones, when no cased letter follows. The two sets are
    # read back from lower() itself: "!cΣ" ends in ς when c is cased and
    # not case-ignorable; "AcΣ" ends in ς when c is either.
    ignorable = lambda c: sigma("A", c) and not sigma("!", c)  # noqa: E731
    cased = lambda c: sigma("!", c)  # noqa: E731
    out = [
        "// Code generated by gen_tables.py from Python " + sys.version.split()[0]
        + " (Unicode " + unicodedata.unidata_version + "). DO NOT EDIT.",
        "",
        "package pystr",
        "",
        "// lowerTable is str.lower() of each code point it changes.",
        *table("lowerTable", str.lower),
        "",
        "// casefoldTable is str.casefold() of each code point it changes.",
        *table("casefoldTable", str.casefold),
        "",
        "// caseIgnorable is Unicode's Case_Ignorable, as str.lower() reads it.",
        *ranges("caseIgnorable", ignorable),
        "",
        "// casedNotIgnorable is Cased, less the case-ignorable code points.",
        *ranges("casedNotIgnorable", cased),
    ]
    target = Path(__file__).with_name("case_gen.go")
    target.write_text("\n".join(out) + "\n", encoding="utf-8")
    subprocess.run(["gofmt", "-w", str(target)], check=True)


if __name__ == "__main__":
    main()
