"""Write names_gen.go: the names re's \\N{...} escape accepts.

    python gen_names.py [NameAliases.txt]

re looks a name up with unicodedata.lookup and takes ord() of the result,
so a name counts when lookup gives exactly one code point. The table holds
every character name of this Python's Unicode database (unicodedata.name,
algorithmic CJK and Hangul names included, which are then left out of the
table and computed in Go) and every alias lookup accepts. Aliases are not
listed by unicodedata, so candidates come from a NameAliases.txt (any
Unicode version) and each is kept only if this Python's lookup accepts it.
The output is gzip-compressed, "NAME;HEX" lines, upper case.
"""

import base64
import gzip
import subprocess
import sys
import unicodedata
from pathlib import Path

aliases_file = Path(sys.argv[1] if len(sys.argv) > 1 else "/usr/share/unicode/ucd/NameAliases.txt")
lines = []
for cp in range(0x110000):
    n = unicodedata.name(chr(cp), None)
    if n is None or n.startswith("CJK UNIFIED IDEOGRAPH-") or n.startswith("HANGUL SYLLABLE "):
        continue
    lines.append(f"{n};{cp:X}")
kept = 0
for raw in aliases_file.read_text().splitlines():
    raw = raw.split("#", 1)[0].strip()
    if not raw:
        continue
    cp, alias = raw.split(";")[:2]
    try:
        got = unicodedata.lookup(alias)
    except KeyError:
        continue
    if len(got) == 1 and ord(got) == int(cp, 16):
        lines.append(f"{alias};{int(cp, 16):X}")
        kept += 1
cjk = []
for cp in range(0x110000):
    if unicodedata.name(chr(cp), "").startswith("CJK UNIFIED IDEOGRAPH-"):
        if cjk and cjk[-1][1] == cp - 1:
            cjk[-1][1] = cp
        else:
            cjk.append([cp, cp])
blob = base64.b64encode(gzip.compress("\n".join(lines).encode(), 9, mtime=0)).decode()
chunks = [blob[i : i + 100] for i in range(0, len(blob), 100)]
out = [
    "// Code generated by gen_names.py from Python "
    + sys.version.split()[0]
    + f" (Unicode {unicodedata.unidata_version}). DO NOT EDIT.",
    "",
    "package pyre",
    "",
    f"// unicodeVersion is the Unicode version of the names below.",
    f'const unicodeVersion = "{unicodedata.unidata_version}"',
    "",
    f"// namesGz is {len(lines)} names ({kept} of them aliases), gzip, base64.",
    "const namesGz = \"\" +",
]
out += [f'\t"{c}" +' for c in chunks[:-1]] + [f'\t"{chunks[-1]}"']
out += ["", "// cjkRanges are the code points named CJK UNIFIED IDEOGRAPH-XXXX.", "var cjkRanges = [][2]rune{"]
out += [f"\t{{0x{a:X}, 0x{b:X}}}," for a, b in cjk] + ["}"]
target = Path(__file__).with_name("names_gen.go")
target.write_text("\n".join(out) + "\n", encoding="utf-8")
subprocess.run(["gofmt", "-w", str(target)], check=True)
print(len(lines), "names,", kept, "aliases,", len(blob), "bytes")
