"""Write the character classes of the SmolVLA tokenizer, for Go
(tables_gen.go here) and Rust (clients/rust/src/smolvla/tables_gen.rs).

    VENV/bin/python clients/go/internal/smolvla/gen_tables.py

VENV is the export environment of clients/vla/requirements.txt. The
classes come from the tokenizers library itself, not from Go's or Rust's
Unicode tables, so they hold the library's own Unicode version:

- letter, number, space: the \\p{L}, \\p{N} and \\s of the ByteLevel
  pre-tokenizer's pattern. A code point that is none of them is "other"
  ([^\\s\\p{L}\\p{N}]).
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import tokenizers
from tokenizers import pre_tokenizers

HERE = Path(__file__).resolve().parent
GO = HERE / "tables_gen.go"
RUST = HERE.parent.parent.parent / "rust" / "src" / "smolvla" / "tables_gen.rs"


def ranges(cps: list[int]) -> list[tuple[int, int]]:
    out: list[list[int]] = []
    for c in cps:
        if out and out[-1][1] == c - 1:
            out[-1][1] = c
        else:
            out.append([c, c])
    return [(a, b) for a, b in out]


def classes() -> dict[str, list[tuple[int, int]]]:
    byte = pre_tokenizers.ByteLevel(add_prefix_space=False, use_regex=True)

    def pieces(pt, s: str) -> int:
        return len(pt.pre_tokenize_str(s))

    got: dict[str, list[int]] = {"letter": [], "number": [], "space": []}
    for c in range(0x110000):
        if 0xD800 <= c <= 0xDFFF:
            continue
        ch = chr(c)
        if pieces(byte, "a" + ch) == 1:
            got["letter"].append(c)
        elif pieces(byte, "0" + ch) == 1:
            got["number"].append(c)
        elif pieces(byte, "!" + ch) != 1:
            got["space"].append(c)
    return {k: ranges(v) for k, v in got.items()}


def go(cls: dict[str, list[tuple[int, int]]]) -> str:
    lines = [
        f"// Code generated by gen_tables.py from tokenizers {tokenizers.__version__}. DO NOT EDIT.",
        "",
        "package smolvla",
        "",
    ]
    for name, rs in cls.items():
        lines.append(f"var {name}Ranges = []rng{{")
        row = []
        for a, b in rs:
            row.append(f"{{0x{a:X}, 0x{b:X}}},")
            if len(row) == 6:
                lines.append("\t" + " ".join(row))
                row = []
        if row:
            lines.append("\t" + " ".join(row))
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def rust(cls: dict[str, list[tuple[int, int]]]) -> str:
    lines = [
        f"// Code generated by gen_tables.py from tokenizers {tokenizers.__version__}. DO NOT EDIT.",
        "",
    ]
    for name, rs in cls.items():
        lines.append(f"pub(super) const {name.upper()}_RANGES: &[(u32, u32)] = &[")
        for a, b in rs:
            lines.append(f"    (0x{a:X}, 0x{b:X}),")
        lines.append("];")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    cls = classes()
    GO.write_text(go(cls))
    subprocess.run(["gofmt", "-w", str(GO)], check=True)
    RUST.write_text(rust(cls))
    print({k: len(v) for k, v in cls.items()})


if __name__ == "__main__":
    main()
