"""Write src/mcpwire/tools_gen.rs: what the oracle's MCP server says about
itself (the tools/list result, the initialize result's fixed parts, the
protocol versions it takes), taken from the oracle and its MCP SDK.

    uv run --no-sync python clients/rust/tools/gen_mcp_tools.py [--check]

The values are the ones clients/go/internal/mcpwire/gen_tools.py takes;
this script writes them as Rust. --check exits 1 when the file on disk is
not what this would write.
"""

from __future__ import annotations

import asyncio
import importlib.metadata
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
OUT = REPO / "clients" / "rust" / "src" / "mcpwire" / "tools_gen.rs"
sys.path.insert(0, str(REPO / "src"))
sys.path.insert(0, str(HERE))

from gen_llm_schemas import rust_string  # noqa: E402 - the sibling generator's quoting


def render() -> str:
    from mcp import types
    from mcp.shared.version import SUPPORTED_PROTOCOL_VERSIONS

    from opendaisugi import Daisugi
    from opendaisugi.mcp_server import build_server

    with tempfile.TemporaryDirectory() as tmp:
        server = build_server(Daisugi(data_dir=Path(tmp)))
        tools = asyncio.run(server.list_tools())
        opts = server._mcp_server.create_initialization_options()
    listed = types.ListToolsResult(tools=tools).model_dump_json(by_alias=True, exclude_none=True)
    caps = opts.capabilities.model_dump_json(by_alias=True, exclude_none=True)
    names = [t.name for t in tools]
    consts = [
        ("TOOLS_LIST", "the tools/list result, as the server writes it", listed),
        ("CAPABILITIES", "the initialize result's capabilities", caps),
        ("SERVER_NAME", "the server's name", opts.server_name),
        ("SERVER_VERSION", "the server's version: the MCP SDK's own", opts.server_version),
        ("INSTRUCTIONS", "the server's instructions", opts.instructions),
        ("LATEST_PROTOCOL", "`types.LATEST_PROTOCOL_VERSION`", types.LATEST_PROTOCOL_VERSION),
        ("SDK_VERSION", "the version of the mcp package", importlib.metadata.version("mcp")),
    ]
    lines = ["// Code generated by tools/gen_mcp_tools.py; DO NOT EDIT.", ""]
    for name, src, value in consts:
        lines += [
            f"/// {src[0].upper() + src[1:]}.",
            f"pub const {name}: &str = {rust_string(value)};",
            "",
        ]
    versions = ", ".join(rust_string(v) for v in SUPPORTED_PROTOCOL_VERSIONS)
    lines += [
        "/// `SUPPORTED_PROTOCOL_VERSIONS`.",
        f"pub const SUPPORTED_PROTOCOLS: &[&str] = &[{versions}];",
        "",
        "/// Each tool's name, in the order tools/list gives them.",
        f"pub const TOOL_NAMES: &[&str] = &[{', '.join(rust_string(n) for n in names)}];",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    # rustfmt lays the file out, as cargo fmt would.
    proc = subprocess.run(
        ["rustfmt", "--edition", "2021"],
        input=render().encode(),
        capture_output=True,
        check=True,
    )
    text = proc.stdout.decode()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print("tools_gen.rs is stale: run gen_mcp_tools.py", file=sys.stderr)
            return 1
        print("tools_gen.rs is current")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
