"""Write src/pathways/potion/tables.rs: what the tokenizers library's
BertNormalizer and BertPreTokenizer do to each code point.

    uv run --no-sync python clients/rust/tools/gen_potion_tables.py [--check]

The tables come from the library itself, not from Rust's char methods,
so they hold the library's own Unicode version. The normalizer config is
the one model2vec's potion models use: clean_text, handle_chinese_chars,
strip_accents unset (so it follows lowercase) and lowercase. --check
fails when the file on disk is not what the library gives now.
"""

from __future__ import annotations

import sys
from pathlib import Path

import tokenizers
from tokenizers import normalizers, pre_tokenizers

OUT = Path(__file__).resolve().parent.parent / "src" / "pathways" / "potion" / "tables.rs"


def ranges(cps: list[int]) -> list[tuple[int, int]]:
    out: list[list[int]] = []
    for c in cps:
        if out and out[-1][1] == c - 1:
            out[-1][1] = c
        else:
            out.append([c, c])
    return [(a, b) for a, b in out]


def hangul(c: int) -> str | None:
    """The NFD of a Hangul syllable, computed, so the table need not list them."""
    s = c - 0xAC00
    if not 0 <= s < 11172:
        return None
    lead, vowel, tail = 0x1100 + s // 588, 0x1161 + (s % 588) // 28, 0x11A7 + s % 28
    return chr(lead) + chr(vowel) + (chr(tail) if tail != 0x11A7 else "")


def rust_str(s: str) -> str:
    return '"' + "".join(f"\\u{{{ord(c):X}}}" for c in s) + '"'


def render() -> str:
    norm = normalizers.BertNormalizer(
        clean_text=True, handle_chinese_chars=True, strip_accents=None, lowercase=True
    )
    pre = pre_tokenizers.BertPreTokenizer()
    removed, space, cjk, ws, punct = [], [], [], [], []
    mapped: list[tuple[int, str]] = []
    for c in range(0x110000):
        if 0xD800 <= c <= 0xDFFF:
            continue
        ch = chr(c)
        r = norm.normalize_str(ch)
        if r != ch:
            if r == "":
                removed.append(c)
            elif r == " ":
                space.append(c)
            elif r == f" {ch} ":
                cjk.append(c)
            elif r != hangul(c):
                mapped.append((c, r))
        parts = pre.pre_tokenize_str("a" + ch + "b")
        if len(parts) == 2:
            ws.append(c)
        elif len(parts) == 3:
            punct.append(c)
    lines = [
        "//! Generated by tools/gen_potion_tables.py from tokenizers "
        + tokenizers.__version__
        + ". Do not edit.",
        "",
    ]

    def table(name: str, doc: str, cps: list[int]) -> None:
        rs = ranges(cps)
        lines.append(f"/// {doc}")
        lines.append(f"pub const {name}: &[(u32, u32)] = &[")
        row = []
        for a, b in rs:
            row.append(f"(0x{a:X}, 0x{b:X}),")
            if len(row) == 6:
                lines.append("    " + " ".join(row))
                row = []
        if row:
            lines.append("    " + " ".join(row))
        lines.append("];")
        lines.append("")

    table("NORM_REMOVED", "Code points clean_text drops.", removed)
    table("NORM_SPACE", "Code points that become one space.", space)
    table("NORM_CJK", "Code points that get a space on each side.", cjk)
    table("PRE_SPACE", "Code points that split words and are dropped (on normalized text).", ws)
    table("PRE_PUNCT", "Code points that are words of their own.", punct)
    lines.append("/// Every other code point the normalizer changes: accents stripped and")
    lines.append("/// lowercased, sorted by code point. Hangul syllables are decomposed in")
    lines.append("/// code.")
    lines.append("pub const NORM_MAPPED: &[(u32, &str)] = &[")
    for c, r in mapped:
        lines.append(f"    (0x{c:X}, {rust_str(r)}),")
    lines.append("];")
    return "\n".join(lines) + "\n"


def main() -> int:
    text = render()
    if "--check" in sys.argv[1:]:
        if OUT.read_text(encoding="utf-8") != text:
            print(f"{OUT.name} is not current; run this script without --check")
            return 1
        print(f"{OUT.name} is current")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
