"""Write src/llm/schemas_gen.rs: the texts the oracle's structured model
calls put in a request, taken from the libraries themselves.

    uv run --no-sync python clients/rust/tools/gen_llm_schemas.py [--check]

The texts are the ones clients/go/internal/llm/gen_schemas.py takes (it
reads them from instructor, pydantic and litellm); this script writes
them as Rust. --check exits 1 when the file on disk is not what this
would write (the libraries or the models changed).
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
OUT = REPO / "clients" / "rust" / "src" / "llm" / "schemas_gen.rs"
GO_GEN = REPO / "clients" / "go" / "internal" / "llm" / "gen_schemas.py"


def rust_string(s: str) -> str:
    """A Rust string literal for s, every character kept."""
    out = ['"']
    for ch in s:
        o = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif o < 0x20 or o == 0x7F:
            out.append(f"\\x{o:02x}")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def render() -> str:
    spec = importlib.util.spec_from_file_location("go_gen_schemas", GO_GEN)
    go = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(go)
    import litellm
    from litellm.llms.anthropic.chat.transformation import AnthropicConfig

    from opendaisugi.distiller import GeneralizedTemplate
    from opendaisugi.models import Envelope

    models = {"GeneralizedTemplate": GeneralizedTemplate, "Envelope": Envelope}
    lines = [
        "// Code generated by tools/gen_llm_schemas.py; DO NOT EDIT.",
        "",
        "/// What instructor's JSON mode appends to the system message, per",
        "/// response model.",
        "pub fn instructor_system(name: &str) -> &'static str {",
        "    match name {",
    ]
    for name, m in models.items():
        lines.append(f"        {rust_string(name)} => {rust_string(go.instructor_suffix(m))},")
    lines += ["        _ => \"\",", "    }", "}", "",
              "/// The schema text the claude-code backend puts in its prompt, per",
              "/// response model.",
              "pub fn claude_schema(name: &str) -> &'static str {",
              "    match name {"]
    for name, m in models.items():
        lines.append(f"        {rust_string(name)} => {rust_string(json.dumps(m.model_json_schema(), indent=2))},")
    lines += ["        _ => \"\",", "    }", "}", "",
              "/// litellm's max_tokens for each Anthropic model it knows by name; any",
              "/// other name gets DEFAULT_MAX_TOKENS.",
              "pub const ANTHROPIC_MAX_TOKENS: &[(&str, i64)] = &["]
    names = sorted(k for k, v in litellm.model_cost.items() if v.get("litellm_provider") == "anthropic")
    for k in names:
        lines.append(f"    ({rust_string(k)}, {AnthropicConfig.get_max_tokens_for_model(k)}),")
    lines += ["];", "", "/// litellm's DEFAULT_ANTHROPIC_CHAT_MAX_TOKENS.",
              f"pub const DEFAULT_MAX_TOKENS: i64 = {AnthropicConfig.get_max_tokens_for_model(None)};", ""]
    return "\n".join(lines)


def main() -> int:
    sys.path.insert(0, str(REPO / "src"))
    text = render()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print("schemas_gen.rs is stale: run gen_llm_schemas.py", file=sys.stderr)
            return 1
        print("schemas_gen.rs is current")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
