"""Write src/envgen/prompts_gen.rs: the prompt texts the oracle's envelope
generation, Tier-1 slot and pathway binding put in a model request, taken
from the oracle itself.

    uv run --no-sync python clients/rust/tools/gen_envgen_prompts.py [--check]

The texts are the ones clients/go/internal/envgen/gen_prompts.py takes;
this script writes them as Rust. --check exits 1 when the file on disk is
not what this would write.
"""

from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
OUT = REPO / "clients" / "rust" / "src" / "envgen" / "prompts_gen.rs"
sys.path.insert(0, str(REPO / "src"))
sys.path.insert(0, str(HERE))

from gen_llm_schemas import rust_string  # noqa: E402 - the sibling generator's quoting


def render() -> str:
    from opendaisugi import envelope, pathway_bind, tier1

    consts = [
        ("PROMPT_VERSION", "envelope.ENVELOPE_PROMPT_VERSION", envelope.ENVELOPE_PROMPT_VERSION),
        ("SYSTEM_PROMPT", "envelope.ENVELOPE_SYSTEM_PROMPT", envelope.ENVELOPE_SYSTEM_PROMPT),
        (
            "SUMMARIZE_INSTRUCTION",
            "envelope._SUMMARIZE_INSTRUCTION",
            envelope._SUMMARIZE_INSTRUCTION,
        ),
        ("TIER1_PROMPT", "tier1._TIER1_PROMPT", tier1._TIER1_PROMPT),
        ("BIND_SYSTEM", "pathway_bind._SYSTEM", pathway_bind._SYSTEM),
    ]
    lines = ["// Code generated by tools/gen_envgen_prompts.py; DO NOT EDIT.", ""]
    for name, src, value in consts:
        lines += [f"/// `{src}`.", f"pub const {name}: &str = {rust_string(value)};", ""]
    return "\n".join(lines)


def main() -> int:
    text = render()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print("prompts_gen.rs is stale: run gen_envgen_prompts.py", file=sys.stderr)
            return 1
        print("prompts_gen.rs is current")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
