#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = []
# ///
"""Write clients/rust/src/gate/py/tables.rs from this Python's own Unicode data.

The Rust gate must read text the way the Python gate does: str.isspace,
str.isalnum (the re module's \\w), str.isdecimal (\\d), str.isdigit,
str.isprintable (repr), str.lower and str.casefold, and the characters
whose NFKC form holds a character urllib refuses in a netloc. Run it
with the oracle's Python, so the tables are that Python's Unicode version:

    .venv/bin/python clients/rust/tools/gen_pytables.py
"""

from __future__ import annotations

import _sre
import sys
import unicodedata
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "src" / "gate" / "py" / "tables.rs"
MAX = sys.maxunicode


def ranges(pred) -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []
    start = None
    for cp in range(MAX + 2):
        hit = cp <= MAX and pred(chr(cp))
        if hit and start is None:
            start = cp
        elif not hit and start is not None:
            out.append((start, cp - 1))
            start = None
    return out


def mapping(fn) -> list[tuple[int, str]]:
    out = []
    for cp in range(MAX + 1):
        c = chr(cp)
        if 0xD800 <= cp <= 0xDFFF:
            continue
        m = fn(c)
        if m != c:
            out.append((cp, m))
    return out


def rs_ranges(name: str, rs: list[tuple[int, int]]) -> str:
    body = ",".join(f"(0x{a:x},0x{b:x})" for a, b in rs)
    return f"pub static {name}: &[(u32, u32)] = &[{body}];\n"


def rs_escape(s: str) -> str:
    return "".join(f"\\u{{{ord(c):x}}}" for c in s)


def rs_map(name: str, m: list[tuple[int, str]]) -> str:
    body = ",".join(f'(0x{cp:x},"{rs_escape(s)}")' for cp, s in m)
    return f"pub static {name}: &[(u32, &str)] = &[{body}];\n"


def sre_lower() -> list[tuple[int, int]]:
    """The re module's own lowercase mapping (_sre.unicode_tolower)."""
    return [(cp, _sre.unicode_tolower(cp)) for cp in range(MAX + 1) if _sre.unicode_tolower(cp) != cp]


def rs_cp_map(name: str, m: list[tuple[int, int]]) -> str:
    body = ",".join(f"(0x{a:x},0x{b:x})" for a, b in m)
    return f"pub static {name}: &[(u32, u32)] = &[{body}];\n"


def rs_extra_cases() -> str:
    """re._casefix._EXTRA_CASES: lowercase characters that match other
    characters under IGNORECASE beyond their own case pair."""
    from re._casefix import _EXTRA_CASES

    rows = []
    for k in sorted(_EXTRA_CASES):
        vals = ",".join(f"0x{v:x}" for v in _EXTRA_CASES[k])
        rows.append(f"(0x{k:x},&[{vals}])")
    return f"pub static SRE_EXTRA_CASES: &[(u32, &[u32])] = &[{','.join(rows)}];\n"


def sigma_cased(c: str) -> bool:
    """Cased, as str.lower's final-sigma rule reads it."""
    return (c + "\u03a3").lower()[-1] == "\u03c2"


def sigma_ignorable(c: str) -> bool:
    """Case-ignorable, as str.lower's final-sigma rule reads it."""
    return ("A" + c + "\u03a3").lower()[-1] == "\u03c2" and not sigma_cased(c)


def main() -> None:
    netloc_bad = "/?#@:"
    parts = [
        "//! Generated by clients/rust/tools/gen_pytables.py from Python "
        f"{sys.version.split()[0]} (Unicode {unicodedata.unidata_version}). Do not edit.\n\n",
        f'pub const PYTHON_VERSION: &str = "{sys.version.split()[0]}";\n',
        f'pub const UNICODE_VERSION: &str = "{unicodedata.unidata_version}";\n',
        rs_ranges("SPACE", ranges(str.isspace)),
        rs_ranges("ALNUM", ranges(str.isalnum)),
        rs_ranges("DECIMAL", ranges(str.isdecimal)),
        rs_ranges("DIGIT", ranges(str.isdigit)),
        rs_ranges("PRINTABLE", ranges(str.isprintable)),
        rs_ranges(
            "NFKC_NETLOC_BAD",
            ranges(lambda c: c.isascii() is False and any(b in unicodedata.normalize("NFKC", c) for b in netloc_bad)),
        ),
        rs_ranges("SRE_CASED", ranges(lambda c: _sre.unicode_iscased(ord(c)))),
        rs_cp_map("SRE_LOWER", sre_lower()),
        rs_extra_cases(),
        rs_ranges("SIGMA_CASED", ranges(sigma_cased)),
        rs_ranges("SIGMA_IGNORABLE", ranges(sigma_ignorable)),
        rs_map("LOWER", mapping(str.lower)),
        rs_map("UPPER", mapping(str.upper)),
        rs_map("CASEFOLD", mapping(str.casefold)),
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
