"""Write prompts_gen.go: the prompt texts the oracle's envelope generation,
Tier-1 slot and pathway binding put in a model request, taken from the
oracle itself.

    uv run --no-sync python clients/go/internal/envgen/gen_prompts.py [--check]

--check exits 1 when the file on disk is not what this would write.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[3] / "src"))
sys.path.insert(0, str(HERE.parent / "llm"))
OUT = HERE / "prompts_gen.go"

from gen_schemas import go_string  # noqa: E402 - the sibling generator's quoting


def render() -> str:
    from opendaisugi import envelope, pathway_bind, tier1

    consts = [
        ("PromptVersion", "envelope.ENVELOPE_PROMPT_VERSION", envelope.ENVELOPE_PROMPT_VERSION),
        ("SystemPrompt", "envelope.ENVELOPE_SYSTEM_PROMPT", envelope.ENVELOPE_SYSTEM_PROMPT),
        (
            "summarizeInstruction",
            "envelope._SUMMARIZE_INSTRUCTION",
            envelope._SUMMARIZE_INSTRUCTION,
        ),
        ("Tier1Prompt", "tier1._TIER1_PROMPT", tier1._TIER1_PROMPT),
        ("bindSystem", "pathway_bind._SYSTEM", pathway_bind._SYSTEM),
    ]
    lines = ["// Code generated by gen_prompts.py; DO NOT EDIT.", "", "package envgen", ""]
    for name, src, value in consts:
        lines += [f"// {name} is {src}.", f"const {name} = {go_string(value)}", ""]
    return "\n".join(lines)


def main() -> int:
    text = render()
    proc = subprocess.run(["gofmt"], input=text.encode(), capture_output=True, check=True)
    text = proc.stdout.decode()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print("prompts_gen.go is stale: run gen_prompts.py", file=sys.stderr)
            return 1
        print("prompts_gen.go is current")
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
