"""Write tools_gen.go: what the oracle's MCP server says about itself (the
tools/list result, the initialize result's fixed parts, the protocol
versions it takes), taken from the oracle and its MCP SDK.

    uv run --no-sync python clients/go/internal/mcpwire/gen_tools.py [--check]

--check exits 1 when the file on disk is not what this would write.
"""

from __future__ import annotations

import asyncio
import importlib.metadata
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[3] / "src"))
sys.path.insert(0, str(HERE.parent / "llm"))
OUT = HERE / "tools_gen.go"

from gen_schemas import go_string  # noqa: E402 - the sibling generator's quoting


def render() -> str:
    from mcp import types
    from mcp.shared.version import SUPPORTED_PROTOCOL_VERSIONS

    from opendaisugi import Daisugi
    from opendaisugi.mcp_server import build_server

    with tempfile.TemporaryDirectory() as tmp:
        server = build_server(Daisugi(data_dir=Path(tmp)))
        tools = asyncio.run(server.list_tools())
        opts = server._mcp_server.create_initialization_options()
    listed = types.ListToolsResult(tools=tools).model_dump_json(by_alias=True, exclude_none=True)
    caps = opts.capabilities.model_dump_json(by_alias=True, exclude_none=True)
    names = [t.name for t in tools]
    consts = [
        ("ToolsList", "the tools/list result, as the server writes it", listed),
        ("Capabilities", "the initialize result's capabilities", caps),
        ("ServerName", "the server's name", opts.server_name),
        ("ServerVersion", "the server's version: the MCP SDK's own", opts.server_version),
        ("Instructions", "the server's instructions", opts.instructions),
        ("LatestProtocol", "types.LATEST_PROTOCOL_VERSION", types.LATEST_PROTOCOL_VERSION),
        ("SDKVersion", "the version of the mcp package", importlib.metadata.version("mcp")),
    ]
    lines = ["// Code generated by gen_tools.py; DO NOT EDIT.", "", "package mcpwire", ""]
    for name, src, value in consts:
        lines += [f"// {name} is {src}.", f"const {name} = {go_string(value)}", ""]
    versions = ", ".join(go_string(v) for v in SUPPORTED_PROTOCOL_VERSIONS)
    lines += [
        "// SupportedProtocols is SUPPORTED_PROTOCOL_VERSIONS.",
        f"var SupportedProtocols = []string{{{versions}}}",
        "",
        "// ToolNames is each tool's name, in the order tools/list gives them.",
        f"var ToolNames = []string{{{', '.join(go_string(n) for n in names)}}}",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    text = render()
    proc = subprocess.run(["gofmt"], input=text.encode(), capture_output=True, check=True)
    text = proc.stdout.decode()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print("tools_gen.go is stale: run gen_tools.py", file=sys.stderr)
            return 1
        print("tools_gen.go is current")
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
